### ISSUE TITLE
How do I run, can we have an install guide?

### ISSUE THREAD

**Issue by arcbtc** [emeceve/nostr-chat#1]
Installed rust then went to nostr-chat/src and did ` rustc main.rs`...getting a bunch of errors

**Comment by arcbtc** [comment]
Ooooo, cd'd into src and did `cargo run main` now its compiling loads of things

**Comment by arcbtc** [comment]
Working now. Can we have an install guide for dummies such as I 
    * Install Rust https://www.rust-lang.org/tools/install
    * cd into /nostr-chat/src and run cargo run main

**Comment by emeceve** [comment]
Build steps added!
