### ISSUE TITLE
build error: could not find system library 'glib-2.0' required by the 'glib-sys' crate

### ISSUE THREAD

**Issue by TristramGreen** [emeceve/nostr-chat#6]
build exited with : 

```
  error: could not find system library 'glib-2.0' required by the 'glib-sys' crate

  --- stderr
  Package glib-2.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `glib-2.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'glib-2.0' found

```

**Comment by TristramGreen** [comment]
I did install `sudo apt install libglib2.0-dev`

but now it says `error: could not find system library 'cairo'`

**Comment by emeceve** [comment]
Hey, @TristramGreen what is your OS?

**Comment by TristramGreen** [comment]
Linux Mint. Thank you, it resolved errors about missing packages.

**Comment by ozkanpakdil** [comment]
@TristramGreen what was missing, I am also having same error in linux mint, wish you shared what you install.

**Comment by codesdad** [comment]
omg.it is really hard to resolve this problem in windows 10.
